###
GET http://localhost:8000/products

###
POST http://localhost:8000/products
Content-Type: application/json

{
  "name": "Carrinho de Rolimã",
  "price": 456.78
}

###
POST http://localhost:8000/products
Content-Type: application/json

{
  "name": "Pipa",
  "price": 90.53
}